#!/usr/bin/env bash
#
# Use rofi/zenity to select display configuration.

# Colors: FG (foreground), BG (background), HL (highlighted)
FG_COLOR="#bbbbbb"
BG_COLOR="#111111"
HLFG_COLOR="#111111"
HLBG_COLOR="#bbbbbb"
BORDER_COLOR="#222222"

# Options not related to colors (most rofi options do not work anymore)
ROFI_OPTIONS=(-theme ~/.config/rofi/powermenu.rasi)
ZENITY_TITLE="Display Configuration"
ZENITY_TEXT="Choose Display Setup:"
ZENITY_OPTIONS=(--column= --hide-header)

# Preferred launcher if both are available
preferred_launcher="rofi"

# Check whether the user-defined launcher is valid
launcher_list=(rofi zenity)
function check_launcher() {
  if [[ ! "${launcher_list[@]}" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
    echo "Supported launchers: ${launcher_list[*]}"
    exit 1
  else
    # Get array with unique elements and preferred launcher first
    i=1
    launcher_list=($(for l in "$1" "${launcher_list[@]}"; do printf "%i %s\n" "$l"; let i+=1; done \
      | sort -uk2 | sort -nk1 | cut -d' ' -f2- | tr '\n' ' '))
  fi
}

# Parse CLI arguments
while getopts "hp:" option; do
  case "${option}" in
    h) echo "${usage}"
       exit 0
       ;;
    p) preferred_launcher="${OPTARG}"
       check_launcher "${preferred_launcher}"
       ;;
    *) exit 1
       ;;
  esac
done

# Check whether a command exists
function command_exists() {
  command -v "$1" &> /dev/null 2>&1
}

# Define the menu options
typeset -A menu

menu=(
  [󰍹   1 TV]="~/.config/polybar/tv.sh"
  [󰍹   2]="~/.config/polybar/2.sh"
  [󰍹   3]="~/.config/polybar/primary.sh"
  [󰍹   3 TV]="~/.config/polybar/3tv.sh"
  [󰍹   4]="~/.config/polybar/all.sh"
  [󰸉   Wallpaper]="~/.config/polybar/wallpaper.sh"
  [   Cancel]=""
)

menu_nrows=${#menu[@]}

launcher_exe=""
launcher_options=""
rofi_colors=""

function prepare_launcher() {
  if [[ "$1" == "rofi" ]]; then
    rofi_colors=(-bc "${BORDER_COLOR}" -bg "${BG_COLOR}" -fg "${FG_COLOR}" \
        -hlfg "${HLFG_COLOR}" -hlbg "${HLBG_COLOR}")
    launcher_exe="rofi"
    launcher_options=(-dmenu -i -lines "${menu_nrows}" -p "${ZENITY_TEXT}" \
        "${rofi_colors}" "${ROFI_OPTIONS[@]}")
  elif [[ "$1" == "zenity" ]]; then
    launcher_exe="zenity"
    launcher_options=(--list --title="${ZENITY_TITLE}" --text="${ZENITY_TEXT}" \
        "${ZENITY_OPTIONS[@]}")
  fi
}

for l in "${launcher_list[@]}"; do
  if command_exists "${l}" ; then
    prepare_launcher "${l}"
    break
  fi
done

# No launcher available
if [[ -z "${launcher_exe}" ]]; then
  exit 1
fi

launcher=(${launcher_exe} "${launcher_options[@]}")
selection="$(printf '%s\n' "${!menu[@]}" | "${launcher[@]}")"

if [[ $? -eq 0 && ! -z ${selection} ]]; then
  if [[ "${menu[${selection}]}" != "" ]]; then
    i3-msg -q "exec --no-startup-id ${menu[${selection}]}"
  fi
fi
