#!/usr/bin/env bash

# Indexed array for menu options (to maintain order)
menu_entries=(
  "  Cancel"
  "󰸉   Wallpaper"
  "󰸉   Shuffle"
  "󰍹   TV"
  "󰍹   --"
  "󰍹   ---"
  "󰍹   -="
  "󰍹   -=-"
)

# Associative array for corresponding commands
declare -A menu_commands=(
  ["  Cancel"]=""
  ["󰸉   Wallpaper"]="~/.config/polybar/wallpaper.sh"
  ["󰸉   Shuffle"]="~/.config/polybar/shuffle_wallpaper.sh"
  ["󰍹   TV"]="~/.config/polybar/tv.sh"
  ["󰍹   --"]="~/.config/polybar/2.sh"
  ["󰍹   ---"]="~/.config/polybar/primary.sh"
  ["󰍹   -="]="~/.config/polybar/3tv.sh"
  ["󰍹   -=-"]="~/.config/polybar/all.sh"
)

# Colors: FG (foreground), BG (background), HL (highlighted)
FG_COLOR="#bbbbbb"
BG_COLOR="#111111"
HLFG_COLOR="#111111"
HLBG_COLOR="#bbbbbb"
BORDER_COLOR="#222222"

# Options not related to colors (most rofi options do not work anymore)
ROFI_OPTIONS=(-theme ~/.config/rofi/powermenu.rasi)

# Whether to ask for user's confirmation
enable_confirmation=false

# Preferred launcher if both are available
preferred_launcher="rofi"

# Check whether a command exists
function command_exists() {
  command -v "$1" &> /dev/null 2>&1
}

# Check whether the user-defined launcher is valid
launcher_list=(rofi zenity)
function check_launcher() {
  if [[ ! "${launcher_list[@]}" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
    echo "Supported launchers: ${launcher_list[*]}"
    exit 1
  else
    i=1
    launcher_list=($(for l in "$1" "${launcher_list[@]}"; do printf "%i %s\n" "$i" "$l"; let i+=1; done \
      | sort -uk2 | sort -nk1 | cut -d' ' -f2- | tr '\n' ' '))
  fi
}

# Prepare the launcher
launcher_exe=""
launcher_options=""
rofi_colors=""

function prepare_launcher() {
  if [[ "$1" == "rofi" ]]; then
    rofi_colors=(-bc "${BORDER_COLOR}" -bg "${BG_COLOR}" -fg "${FG_COLOR}" \
        -hlfg "${HLFG_COLOR}" -hlbg "${HLBG_COLOR}")
    launcher_exe="rofi"
    launcher_options=(-dmenu -i -lines "${#menu_entries[@]}" -p "Select Display Option" \
        "${rofi_colors}" "${ROFI_OPTIONS[@]}")
  elif [[ "$1" == "zenity" ]]; then
    launcher_exe="zenity"
    launcher_options=(--list --title="Display Menu" --text="Select Display Option:" \
        --column="Options" "${menu_entries[@]}")
  fi
}

for l in "${launcher_list[@]}"; do
  if command_exists "${l}" ; then
    prepare_launcher "${l}"
    break
  fi
done

# No launcher available
if [[ -z "${launcher_exe}" ]]; then
  exit 1
fi

launcher=(${launcher_exe} "${launcher_options[@]}")

# Generate the menu dynamically based on the indexed array
selection="$(printf '%s\n' "${menu_entries[@]}" | "${launcher[@]}")"

# Execute the corresponding command if a valid selection is made
if [[ -n "${selection}" && -n "${menu_commands[$selection]}" ]]; then
  eval "${menu_commands[$selection]}"
fi
